// Generate static HTML, browser assets and the disposable Render publish directory.
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { categories, loadCatalogue } from '../src/catalogue.mjs';
import {
  home,
  categoriesPage,
  cataloguePage,
  productPage,
  aboutPage,
  contactPage,
} from '../src/templates.mjs';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
// Resolve source data once so every page and export uses the same records.
const products = loadCatalogue(root);
// Generated HTML is stamped with its source location to discourage manual edits.
const write = (file, html) => {
  const target = path.join(root, file);
  fs.mkdirSync(path.dirname(target), { recursive: true });
  fs.writeFileSync(
    target,
    file.endsWith('.html')
      ? html.replace(
          '<!doctype html>',
          '<!doctype html>\n<!-- Generated by scripts/build.mjs from src/templates.mjs. Edit src/ and rebuild. -->\n',
        )
      : html,
  );
};
write(
  'products.js',
  `// Generated catalogue data. Edit src/data/ and rebuild.\nwindow.ROSHAN_PRODUCTS = ${JSON.stringify(products, null, 2)};\n`,
);
// Copy browser source to the root for a server-free local preview.
for (const file of ['styles.css', 'modern.css', 'app.js'])
  fs.copyFileSync(path.join(root, 'src', file), path.join(root, file));
write('index.html', home(products));
write('catalogue.html', cataloguePage(products));
write('categories.html', categoriesPage(products));
write('about.html', aboutPage(products));
write('contact.html', contactPage());
for (const c of categories) write(`categories/${c.id}.html`, cataloguePage(products, c));
for (const p of products) write(p.url, productPage(p, products));
// Quote each CSV field so punctuation in product names remains safe.
const csvCell = (value) => '"' + String(value).replaceAll('"', '""') + '"';
write(
  'product-skus.csv',
  [
    'SKU,Product,Category,Family,Catalogue Reference,PDF Page',
    ...products.map((p) =>
      [p.sku, p.name, p.category, p.family, p.id.toUpperCase(), p.page].map(csvCell).join(','),
    ),
  ].join('\n'),
);
// dist is a disposable hosting copy, never an editable source directory.
const output = path.join(root, 'dist');
// Recreate only the verified build directory so removed files cannot survive deployments.
if (fs.existsSync(output)) {
  if (path.relative(root, fs.realpathSync(output)) !== 'dist')
    throw new Error('Refusing to clean a build directory outside this project');
  fs.rmSync(output, { recursive: true });
}
fs.mkdirSync(output, { recursive: true });
for (const file of [
  'index.html',
  'catalogue.html',
  'categories.html',
  'about.html',
  'contact.html',
  'styles.css',
  'modern.css',
  'app.js',
  'products.js',
  'product-skus.csv',
])
  fs.copyFileSync(path.join(root, file), path.join(output, file));
for (const dir of ['assets', 'categories', 'products'])
  fs.cpSync(path.join(root, dir), path.join(output, dir), { recursive: true });
console.log(
  `Built ${products.length} product pages, ${categories.length} category pages and 5 main pages. Stable SKUs saved to sku-map.json.`,
);
