// Generate static HTML, browser assets and the disposable Render publish directory.
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { writeBrowserAssets } from './browser-build.mjs';
import { categories, loadCatalogue } from '../src/catalogue.mjs';
import {
  home,
  categoriesPage,
  cataloguePage,
  productPage,
  aboutPage,
  contactPage,
  newArrivalsPage,
  founderPage,
  officesPage,
} from '../src/templates.mjs';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
// Generated HTML is stamped with its source location to discourage manual edits.
const write = (file, html) => {
  const target = path.join(root, file);
  fs.mkdirSync(path.dirname(target), { recursive: true });
  fs.writeFileSync(
    target,
    file.endsWith('.html')
      ? html.replace(
          '<!doctype html>',
          '<!doctype html>\n<!-- Generated by scripts/build.mjs from src/templates.mjs. Edit src/ and rebuild. -->\n',
        )
      : html,
  );
};
/** Write complete export records and the six main routes. */
function writeMainPages(products) {
  write(
    'products.js',
    `// Generated catalogue data. Edit src/data/ and rebuild.\nwindow.ROSHAN_PRODUCTS = ${JSON.stringify(products, null, 2)};\n`,
  );
  writeBrowserAssets(root, products);
  write('index.html', home(products));
  write('catalogue.html', cataloguePage(products));
  write('categories.html', categoriesPage(products));
  write('about.html', aboutPage(products));
  write('contact.html', contactPage());
  write('new-arrivals.html', newArrivalsPage(products));
  write('founder.html', founderPage());
  write('offices.html', officesPage());
}

/** Remove only verified generated routes that no longer exist in the catalogue. */
function removeRetiredRoutes(products) {
  // Remove the retired generated route from local previews as well as deployment output.
  const retiredCreditsPage = path.join(root, 'photo-credits.html');
  if (fs.existsSync(retiredCreditsPage)) fs.unlinkSync(retiredCreditsPage);
  // Remove obsolete generated routes so local previews and hosting agree.
  for (const [directory, expected] of [
    ['products', new Set(products.map((p) => path.basename(p.url)))],
    ['categories', new Set(categories.map((c) => c.id + '.html'))],
  ]) {
    const location = path.join(root, directory);
    // Generated folders are absent on a fresh Git checkout, including Render builds.
    // The page writer creates them below; there are no stale routes to remove yet.
    if (!fs.existsSync(location)) continue;
    if (path.relative(root, fs.realpathSync(location)) !== directory)
      throw new Error('Unexpected generated directory');
    for (const file of fs.readdirSync(location))
      if (file.endsWith('.html') && !expected.has(file)) {
        const target = path.join(location, file);
        if (!fs.readFileSync(target, 'utf8').includes('Generated by scripts/build.mjs'))
          throw new Error('Refusing to remove an ungenerated route ' + file);
        fs.unlinkSync(target);
      }
  }
}

/** Generate category and product routes with a stable SKU reference CSV. */
function writeCataloguePages(products) {
  for (const c of categories) write(`categories/${c.id}.html`, cataloguePage(products, c));
  for (const p of products) write(p.url, productPage(p, products));
  // Quote each CSV field so punctuation in product names remains safe.
  const csvCell = (value) => '"' + String(value).replaceAll('"', '""') + '"';
  write(
    'product-skus.csv',
    [
      'SKU,Product,Category,Family,Source Reference,Catalogue Page,Source PDF Page',
      ...products.map((p) =>
        [p.sku, p.name, p.category, p.family, p.sourcePanel, p.cataloguePage, p.page]
          .map(csvCell)
          .join(','),
      ),
    ].join('\n'),
  );
}

/** Recreate the confined, disposable hosting directory. */
function publishDirectory(products) {
  // dist is a disposable hosting copy, never an editable source directory.
  const output = path.join(root, 'dist');
  // Recreate only the verified build directory so removed files cannot survive deployments.
  if (fs.existsSync(output)) {
    if (path.relative(root, fs.realpathSync(output)) !== 'dist')
      throw new Error('Refusing to clean a build directory outside this project');
    fs.rmSync(output, { recursive: true });
  }
  fs.mkdirSync(output, { recursive: true });
  for (const file of [
    'index.html',
    'catalogue.html',
    'categories.html',
    'about.html',
    'contact.html',
    'new-arrivals.html',
    'founder.html',
    'offices.html',
    'styles.css',
    'modern.css',
    'app.js',
    'products.js',
    'browser-products.js',
    'site.css',
    'product-skus.csv',
    'Roshan-Industries-Product-Catalogue.xlsx',
  ])
    fs.copyFileSync(path.join(root, file), path.join(output, file));
  for (const dir of ['assets', 'categories', 'products'])
    fs.cpSync(path.join(root, dir), path.join(output, dir), { recursive: true });
  // Visitors need the same records without development indentation; local exports stay readable.
  fs.writeFileSync(
    path.join(output, 'products.js'),
    `// Generated catalogue data. Edit src/data/ and rebuild.\nwindow.ROSHAN_PRODUCTS = ${JSON.stringify(products)};\n`,
  );
}

/** Build from one validated catalogue snapshot. No writes occur when this module is imported. */
export function buildSite() {
  const products = loadCatalogue(root);
  console.log(`[build] Loaded ${products.length} validated products. Generating pages...`);
  writeMainPages(products);
  removeRetiredRoutes(products);
  writeCataloguePages(products);
  publishDirectory(products);
  console.log(
    `[build] Ready: ${products.length} product pages, ${categories.length} category pages and 8 main pages in dist/. Permanent SKUs validated against src/data/sku-map.json.`,
  );
}

if (process.argv[1] && path.resolve(process.argv[1]) === fileURLToPath(import.meta.url))
  buildSite();
